#It is for development server, so it doesn't require or mandatory to specify real secret key

#part 1 to create django project using docker-compose
# version: '3.9'

# services:
#   #Editable but best to set it like this one
#   app:
#     build:
#       context: .
#     ports:
#       - 8000:8000
#     volumes:
#       #Editable(with .) like .:/app
#       - ./app:/app


#after configuring the wait_for_db.py
version: '3.9'

services:
  #Editable but best to set it like this one
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      #Editable(with .) like .:/app
      - ./app:/app
      # - ./data/web:/vol/web:z
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme